// Code generated by protoc-gen-wasmify-go. DO NOT EDIT.

package internal

import (
	"encoding/binary"
	"errors"
	"fmt"
	"math"
	"os"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"

	"github.com/goccy/llamawasm2go"
	"github.com/goccy/llamawasm2go/base"
)

var (
	_ = binary.LittleEndian
	_ = errors.New
	_ = fmt.Errorf
	_ = math.Float32bits
	_ = os.Stderr
	_ = runtime.SetFinalizer
	_ = sort.Search
	_ = strconv.Itoa
	_ = strings.TrimSpace
	_ = sync.Once{}
	_ = wasm2go.Memory
	_ *base.Module
)

// pbNewBuf returns the scratch buffer every request marshal starts
// from. Starting from a presized slice instead of nil removes the
// append growth ladder (nil→8→16→… reallocations plus copies) that
// made runtime.growslice-under-pbAppendVarint 90% of one hot
// consumer's slice-growth profile; 64 bytes covers the dominant
// single-handle request shape (≤ 13 bytes) and small argument
// messages in one allocation. A sync.Pool variant was measured and
// REJECTED: the per-call Get/Put traffic and the pointer box each
// Put allocates cost more time than the saved reallocations
// (isolated A/B on googlesqlite's window suite: allocs/op −15% but
// sec/op +1.5%, B/op +4.8%).
func pbNewBuf() []byte { return make([]byte, 0, 64) }

// pbVarintLen reports the encoded size of v without writing it.
func pbVarintLen(v uint64) int {
	n := 1
	for v >= 0x80 {
		v >>= 7
		n++
	}
	return n
}

// pbAppendVarint appends a varint-encoded uint64.
func pbAppendVarint(buf []byte, v uint64) []byte {
	for v >= 0x80 {
		buf = append(buf, byte(v)|0x80)
		v >>= 7
	}
	return append(buf, byte(v))
}

// pbAppendTag appends a field tag.
func pbAppendTag(buf []byte, field, wireType uint32) []byte {
	return pbAppendVarint(buf, uint64(field<<3|wireType))
}

func pbAppendUint64(buf []byte, field uint32, v uint64) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, v)
}

func pbAppendInt32(buf []byte, field uint32, v int32) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, uint64(v))
}

func pbAppendInt64(buf []byte, field uint32, v int64) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, uint64(v))
}

func pbAppendBool(buf []byte, field uint32, v bool) []byte {
	buf = pbAppendTag(buf, field, 0)
	if v {
		return append(buf, 1)
	}
	return append(buf, 0)
}

func pbAppendString(buf []byte, field uint32, s string) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(s)))
	return append(buf, s...)
}

func pbAppendBytes(buf []byte, field uint32, data []byte) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(data)))
	return append(buf, data...)
}

func pbAppendFloat(buf []byte, field uint32, v float32) []byte {
	buf = pbAppendTag(buf, field, 5)
	var tmp [4]byte
	binary.LittleEndian.PutUint32(tmp[:], math.Float32bits(v))
	return append(buf, tmp[:]...)
}

func pbAppendDouble(buf []byte, field uint32, v float64) []byte {
	buf = pbAppendTag(buf, field, 1)
	var tmp [8]byte
	binary.LittleEndian.PutUint64(tmp[:], math.Float64bits(v))
	return append(buf, tmp[:]...)
}

func pbAppendSubmessage(buf []byte, field uint32, sub []byte) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(sub)))
	return append(buf, sub...)
}

func pbAppendHandle(buf []byte, field uint32, ptr uint64) []byte {
	// The submessage has a fixed shape — tag(1,varint) + varint(ptr),
	// ≤ 11 bytes — so its length is computable up front and the
	// whole thing can be written straight into buf. The previous
	// shape built the inner bytes in a fresh slice per call
	// (`pbAppendUint64(nil, …)`), one heap allocation per handle
	// field on every bridge call.
	inner := 1 + pbVarintLen(ptr)
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(inner))
	buf = append(buf, 0x08) // field 1, wire type varint
	return pbAppendVarint(buf, ptr)
}

// pbAppendHandlePtr is the nil-safe one-line wrapper around
// pbAppendHandle. Generic + comparable lets it accept any
// pointer-typed wrapper that provides rawPtr() and short-circuit
// when the pointer is nil. The caller writes
//
//	buf = pbAppendHandlePtr(buf, N, v.X)
//
// which gofmt keeps as one line; the alternative
//
//	if v.X != nil { buf = pbAppendHandle(buf, N, v.X.rawPtr()) }
//
// is gofmt-expanded to three lines per occurrence and accounts
// for several hundred KB of bloat across the binding.
func pbAppendHandlePtr[T interface {
	comparable
	rawPtr() uint64
}](buf []byte, field uint32, v T) []byte {
	var zero T
	if v == zero {
		return buf
	}
	return pbAppendHandle(buf, field, v.rawPtr())
}

// pbAppendSubmessagePtr is the value-type-message counterpart of
// pbAppendHandlePtr: nil-safe, gofmt-friendly one-liner around
// pbAppendSubmessage + the type's marshal() helper.
func pbAppendSubmessagePtr[T interface {
	comparable
	marshal() []byte
}](buf []byte, field uint32, v T) []byte {
	var zero T
	if v == zero {
		return buf
	}
	return pbAppendSubmessage(buf, field, v.marshal())
}

// clearPtrAny is the gofmt-friendly nil-safe ownership-transfer
// helper for handle parameters. Replaces the inline expansion
//
//	if c, ok := v.(interface{ clearPtr() }); ok { c.clearPtr() }
//
// (3 lines after gofmt) plus its surrounding nil-guard with a
// single function call. Handles both interface values
// (CatalogNode et al) and concrete pointers; the type assertion
// short-circuits when v is a true-nil interface, and the wrapped
// clearPtr() is itself nil-receiver-safe so a typed-nil pointer
// passed through the interface no-ops cleanly.
func clearPtrAny(v any) {
	if c, ok := v.(interface{ clearPtr() }); ok {
		c.clearPtr()
	}
}

// clearPtrAll is the slice variant of clearPtrAny. Used when the
// proto-field's wire shape is repeated-handle and the C++ side
// adopts ownership of every element. Each element runs through
// the same type-assertion shortcut so the helper handles
// concrete-pointer slices, interface slices, and slices that mix
// nil and non-nil entries uniformly.
func clearPtrAll[T any](items []T) {
	for _, item := range items {
		clearPtrAny(item)
	}
}

// pbReader is a streaming protobuf decoder.
type pbReader struct {
	data []byte
	pos  int
}

func (r *pbReader) hasData() bool { return r.pos < len(r.data) }

func (r *pbReader) readVarint() uint64 {
	var v uint64
	var shift uint
	for r.pos < len(r.data) {
		b := r.data[r.pos]
		r.pos++
		v |= uint64(b&0x7f) << shift
		if b < 0x80 {
			return v
		}
		shift += 7
	}
	return v
}

func (r *pbReader) next() (field, wireType uint32, ok bool) {
	if !r.hasData() {
		return 0, 0, false
	}
	tag := r.readVarint()
	return uint32(tag >> 3), uint32(tag & 7), true
}

func (r *pbReader) readString() string {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	s := string(r.data[r.pos : r.pos+n])
	r.pos += n
	return s
}

func (r *pbReader) readBytes() []byte {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	b := make([]byte, n)
	copy(b, r.data[r.pos:r.pos+n])
	r.pos += n
	return b
}

func (r *pbReader) readBool() bool {
	return r.readVarint() != 0
}

func (r *pbReader) readInt32() int32 {
	return int32(r.readVarint())
}

func (r *pbReader) readInt64() int64 {
	return int64(r.readVarint())
}

func (r *pbReader) readUint32() uint32 {
	return uint32(r.readVarint())
}

func (r *pbReader) readUint64() uint64 {
	return r.readVarint()
}

func (r *pbReader) readFloat() float32 {
	if r.pos+4 > len(r.data) {
		r.pos = len(r.data)
		return 0
	}
	v := binary.LittleEndian.Uint32(r.data[r.pos : r.pos+4])
	r.pos += 4
	return math.Float32frombits(v)
}

func (r *pbReader) readDouble() float64 {
	if r.pos+8 > len(r.data) {
		r.pos = len(r.data)
		return 0
	}
	v := binary.LittleEndian.Uint64(r.data[r.pos : r.pos+8])
	r.pos += 8
	return math.Float64frombits(v)
}

func (r *pbReader) readSubmessage() *pbReader {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	sub := &pbReader{data: r.data[r.pos : r.pos+n]}
	r.pos += n
	return sub
}

func (r *pbReader) skip(wireType uint32) {
	switch wireType {
	case 0: // varint
		r.readVarint()
	case 1: // 64-bit
		r.pos += 8
	case 2: // length-delimited
		n := int(r.readVarint())
		r.pos += n
	case 5: // 32-bit
		r.pos += 4
	}
	if r.pos > len(r.data) {
		r.pos = len(r.data)
	}
}

// pbExtractError scans a response for field 15 (error string).
func pbExtractError(resp []byte) error {
	r := &pbReader{data: resp}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 15 {
			return errors.New(r.readString())
		}
		r.skip(w)
	}
	return nil
}

// readHandlePtr reads the ptr from a response. Handles two patterns:
// 1. Direct varint: field 1, wireType 0 → read varint directly
// 2. Submessage: field 1, wireType 2 → read submessage, then field 1 varint inside
func readHandlePtr(data []byte) uint64 {
	r := &pbReader{data: data}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 1 {
			if w == 0 {
				// Direct varint (constructor pattern)
				return r.readVarint()
			}
			if w == 2 {
				// Submessage (write_handle pattern)
				sub := r.readSubmessage()
				for sf, sw, sok := sub.next(); sok; sf, sw, sok = sub.next() {
					if sf == 1 && sw == 0 {
						return sub.readVarint()
					}
					sub.skip(sw)
				}
			}
			return 0
		}
		r.skip(w)
	}
	return 0
}

// readPtrAtField returns the handle pointer encoded at response field f.
// f == 1 takes the fast path via readHandlePtr (which already handles
// both the direct-varint constructor shape and the submessage write_handle
// shape); other fields are walked once to find the correct submessage.
// Returns 0 if the field is not present, which is the standard "absent
// handle" sentinel — callers translate that to (nil, nil).
func readPtrAtField(resp []byte, f uint32) uint64 {
	if f == 1 {
		return readHandlePtr(resp)
	}
	pr := &pbReader{data: resp}
	for ff, w, ok := pr.next(); ok; ff, w, ok = pr.next() {
		if ff == f {
			if w == 2 {
				sub := pr.readSubmessage()
				return readHandlePtr(sub.data)
			}
			return 0
		}
		pr.skip(w)
	}
	return 0
}

// decodeChildHandle is the standard accessor-return shape. It reads
// the handle pointer at field f, returns nil for missing/zero, and
// otherwise constructs the child via ctor and pins the parent (owner)
// onto it via setKeepAlive when owner is non-nil. Constructor-style
// callers (free functions) pass owner=nil; accessors pass the
// receiver. The child must already implement the unexported keepAlive
// interface, which every generated handle struct does.
func decodeChildHandle[T any](resp []byte, field uint32, owner any, ctor func(uint64) *T) *T {
	ptr := readPtrAtField(resp, field)
	if ptr == 0 {
		return nil
	}
	child := ctor(ptr)
	if owner != nil {
		if ka, ok := any(child).(interface{ setKeepAlive(any) }); ok {
			ka.setKeepAlive(owner)
		}
	}
	return child
}

// decodeAbstractAs is the abstract-return counterpart of
// decodeChildHandle: read field f, look up the runtime concrete type
// via resolveAbstractHandle, type-assert to I, attach keepAlive when
// owner is non-nil. ifaceName is only used in the error message when
// the runtime type does not satisfy I (which is a real bug, not a
// "missing field" condition).
func decodeAbstractAs[I any](resp []byte, field uint32, owner any, ifaceName string) (I, error) {
	var z I
	ptr := readPtrAtField(resp, field)
	if ptr == 0 {
		return z, nil
	}
	resolved, err := resolveAbstractHandle(ptr)
	if err != nil {
		return z, err
	}
	if v, ok := resolved.(I); ok {
		if owner != nil {
			if ka, okKA := any(v).(interface{ setKeepAlive(any) }); okKA {
				ka.setKeepAlive(owner)
			}
		}
		return v, nil
	}
	return z, fmt.Errorf("resolved type %T does not implement %s", resolved, ifaceName)
}

// readScalarAtField walks resp once for field f and reads the value via
// the read closure. Missing field returns the zero value. The closure is
// always one of (*pbReader).readBool / readInt32 / readInt64 / readUint32
// / readUint64 / readFloat / readDouble / readString / readBytes - small
// values, but they fold the per-method scan-and-read loop into one call
// site.
func readScalarAtField[T any](resp []byte, f uint32, read func(*pbReader) T) T {
	var z T
	pr := &pbReader{data: resp}
	for ff, w, ok := pr.next(); ok; ff, w, ok = pr.next() {
		if ff == f {
			return read(pr)
		}
		pr.skip(w)
	}
	return z
}

// factoryFor curries a typed constructor (newXNoFinalizer) into the
// untyped factory shape stored in cppTypeFactories. Without it the
// generated cppTypeToGoType map had to repeat
//
//	"googlesql::Foo": func(ptr uint64) any { return newFooNoFinalizer(ptr) }
//
// per concrete type — ~1,400 structurally-identical closures.
func factoryFor[T any](ctor func(uint64) *T) func(uint64) any {
	return func(ptr uint64) any { return ctor(ptr) }
}

// enumString backs the per-enum String() methods. Generated code emits
// parallel _vals_<E> []int32 and _names_<E> []string slices keyed in
// canonical order; this helper does a linear scan and falls back to
// the decimal form for values that aren't in the table (forward
// compatibility when new values land before regeneration).
func enumString(v int32, vals []int32, names []string) string {
	for i, x := range vals {
		if x == v {
			return names[i]
		}
	}
	return strconv.Itoa(int(v))
}

var _ = errors.New
var _ = binary.LittleEndian
var _ = fmt.Errorf
var _ = math.Float32bits
var _ = strconv.Itoa

// Module is the bridge handle. It wraps the wasm2go-transpiled module
// (*base.Module) and serialises every entry on m.mu.
//
// Reentrant callbacks — a host-import callback whose handler needs
// to make further calls back into the transpiled module — are
// supported by releasing m.mu around the user handler in
// handleCallback.
//
// Safety rests on a single structural property: every path that
// touches transpiled module state goes through m.invoke, and
// m.invoke holds m.mu for the entire duration of its call. The
// release window in handleCallback simply lets another m.invoke
// grab the mutex and run as a fully nested top-level call — same
// goroutine via the user handler, different goroutine via an
// unrelated caller, it doesn't matter. Either way the nested call
// enters, balances its own state changes, and exits before the
// outer call resumes, so the outer call never observes a mid-flight
// inner call.
type Module struct {
	// mu serialises every entry into the transpiled module (invoke +
	// nested re-entry from inside a callback handler).
	mu sync.Mutex
	g  *base.Module
	// cbMu guards callbacks and nextCBID. RWMutex because lookup in
	// handleCallback is hot (every host-import dispatch) while
	// Register/Unregister are rare (typically once per lifetime of a
	// registered Go-side handler). Held only for the brief map op;
	// never held while running user code or the transpiled module,
	// so it never participates in the m.mu -> transpiled-module ->
	// handleCallback chain and cannot deadlock against it.
	cbMu      sync.RWMutex
	callbacks map[int32]CallbackHandler
	nextCBID  int32
	// cbDesc is the reusable guest-memory result descriptor for callback
	// returns on a memory64 module (see encodeCallbackResult); 0 until
	// first use, and never touched on wasm32.
	cbDesc wptr
}

// wptr is the guest pointer width: int32 for a wasm32 module, int64
// for a memory64 (wasm64) one. Every pointer or length that crosses
// the bridge boundary is a wptr; the transpiled wasm2go package's
// export/import signatures use the same width, so the two packages
// stay in lock-step from the one substitution the generator makes.
type wptr = int64

var (
	globalModule *Module
	initOnce     sync.Once
	initErr      error
)

// CallbackHandler is implemented by Go types that need to be called from C++.
// The type is always defined (the Module struct references it); the
// registration/dispatch machinery is only emitted when the wasm imports
// wasmify.callback_invoke.
type CallbackHandler interface {
	HandleCallback(methodID int32, req []byte) ([]byte, error)
}

// Options configure the module the generated API runs on. The zero
// value is what Init uses: the default WASI implementation (the host
// filesystem, environment and stdio), the engine's own initial memory
// reservation, and its wasm32 4 GiB ceiling.
type Options struct {
	// WASI replaces the wasi_snapshot_preview1 implementation the guest
	// runs against. base.DefaultWASI() returns the default one, whose
	// setters scope the filesystem to a directory (or an arbitrary
	// base.FS), replace the environment and redirect stdio; any
	// implementation of the interface will do. nil keeps the default.
	WASI base.Wasi_snapshot_preview1Imports

	// MemoryReserveBytes pre-reserves linear memory. A guest that grows
	// to a size known up front — loading a large model or data file —
	// otherwise reallocates and copies the whole linear memory as it
	// goes. Zero keeps the engine's default headroom.
	MemoryReserveBytes int

	// MaxMemoryBytes caps linear-memory growth, so a workload bigger
	// than expected fails inside the guest (memory.grow returns -1)
	// instead of growing the host process. Zero keeps the engine's own
	// ceiling.
	MaxMemoryBytes uint64
}

// Init initializes the global module with the default Options. Must be
// called before any API use. Safe to call multiple times (uses
// sync.Once).
func Init() error { return InitWith(Options{}) }

// InitWith initializes the global module with opts. Like Init it runs at
// most once per process: the module owns one linear memory and one C
// heap, so there is exactly one instance and the first initialization
// wins. A later call — with any Options — returns that instance's
// initialization result without reconfiguring it.
func InitWith(opts Options) error {
	initOnce.Do(func() {
		initErr = initModule(opts)
	})
	return initErr
}

// module returns the initialized global module. Panics if Init was not
// called.
func module() *Module {
	if globalModule == nil {
		panic("wasmify: Init() must be called before using any API")
	}
	return globalModule
}

// Instance returns the transpiled module the global API runs on, or nil
// before initialization.
//
// It exists for base.AccessMemory, which is the only safe way to read or
// write linear memory from a goroutine other than the one running a call
// — an interrupt flag an embedder raises while a long call is in flight,
// a progress word it polls. Everything else should go through the
// generated API: calling into the module directly bypasses the lock that
// serialises entries and the C stack would be shared with the call in
// progress.
func Instance() *base.Module {
	if globalModule == nil {
		return nil
	}
	return globalModule.g
}

func initModule(opts Options) (retErr error) {
	m := &Module{}
	env := envStubs{m: m}
	wm := wasmifyStubs{m: m}
	wasi := opts.WASI
	if wasi == nil {
		wasi = base.DefaultWASI()
	}
	if opts.MemoryReserveBytes > 0 {
		m.g = wasm2go.NewWithWASIReserve(wasi, env, wm, opts.MemoryReserveBytes)
	} else {
		m.g = wasm2go.NewWithWASI(wasi, env, wm)
	}
	if opts.MaxMemoryBytes > 0 {
		wasm2go.SetMaxMemory(m.g, opts.MaxMemoryBytes)
	}
	// Set globalModule eagerly so the rest of the API can run even if
	// _initialize panics partway through C++ static-initializer code.
	globalModule = m
	defer func() {
		if r := recover(); r != nil {
			retErr = fmt.Errorf("init panicked: %v", r)
		}
	}()
	wasm2go.Initialize(m.g)
	_ = wasm2go.WasmInit(m.g)
	return nil
}

// invoke serializes req into wasm memory, runs the per-export caller
// (wasm2go.Inv_<svc>_<mt>), and unpacks the response via decodeResult.
// call is the trap-safe per-export entry point: it snapshots and
// restores the mutable wasm globals so a mid-call panic does not leak
// an abandoned C++ activation frame.
func (m *Module) invoke(serviceID, methodID int32, req []byte, call func(*base.Module, wptr, wptr) (int64, error)) ([]byte, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var reqPtr, reqLen wptr
	if len(req) > 0 {
		reqPtr = wasm2go.WasmAlloc(m.g, wptr(len(req)))
		reqLen = wptr(len(req))
		// Free reqPtr unconditionally on return so the request
		// buffer never lingers in wasm memory when the call traps
		// or the early-exit branches below fire. Guard against
		// the WasmAlloc-returned-zero case: free(NULL) is a
		// dlmalloc no-op but C++ allocators are less consistent.
		if reqPtr != 0 {
			defer wasm2go.WasmFree(m.g, reqPtr)
		}
		copy(wasm2go.Memory(m.g)[wptrOff(reqPtr):], req)
	}
	packed, err := call(m.g, reqPtr, reqLen)
	if err != nil {
		return nil, err
	}
	respPtr, respLen := decodeResult(m.g, packed)
	if respLen == 0 {
		return nil, nil
	}
	mem := wasm2go.Memory(m.g)
	out := make([]byte, respLen)
	copy(out, mem[respPtr:respPtr+respLen])
	wasm2go.WasmFree(m.g, wptr(respPtr))
	return out, nil
}

// resolveTypeName calls the C++ bridge to get the runtime type name of
// the object at ptr. Returns a fully qualified C++ class name.
func (m *Module) resolveTypeName(ptr uint64) (string, error) {
	buf := pbAppendUint64(pbNewBuf(), 1, ptr)
	m.mu.Lock()
	defer m.mu.Unlock()
	reqPtr := wasm2go.WasmAlloc(m.g, wptr(len(buf)))
	copy(wasm2go.Memory(m.g)[wptrOff(reqPtr):], buf)
	packed := wasm2go.WasmifyGetTypeName(m.g, reqPtr, wptr(len(buf)))
	respPtr, respLen := decodeResult(m.g, packed)
	defer wasm2go.WasmFree(m.g, reqPtr)
	if respLen == 0 {
		return "", nil
	}
	resp := make([]byte, respLen)
	copy(resp, wasm2go.Memory(m.g)[respPtr:respPtr+respLen])
	defer wasm2go.WasmFree(m.g, wptr(respPtr))
	if e := pbExtractError(resp); e != nil {
		return "", e
	}
	r := &pbReader{data: resp}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 1 {
			return r.readString(), nil
		}
		r.skip(w)
	}
	return "", nil
}

// invokeMethod fans the wasm call out into the runtime, then folds in
// the (very common) pbExtractError check on the response. call is the
// per-export wasm2go.Inv_<svc>_<mt> entry point.
func invokeMethod(svc, mid int32, req []byte, call func(*base.Module, wptr, wptr) (int64, error)) ([]byte, error) {
	resp, err := module().invoke(svc, mid, req, call)
	if err != nil {
		return nil, err
	}
	if e := pbExtractError(resp); e != nil {
		return nil, e
	}
	return resp, nil
}

// wptrOff widens a guest pointer to an unsigned slice offset.
func wptrOff(p wptr) uint64 {
	return uint64(p)
}

func decodeResult(g *base.Module, packed int64) (uint64, uint64) {
	if packed == 0 {
		return 0, 0
	}
	mem := wasm2go.Memory(g)
	d := uint64(packed)
	return binary.LittleEndian.Uint64(mem[d:]), binary.LittleEndian.Uint64(mem[d+8:])
}

func encodeCallbackResult(m *Module, resp []byte) int64 {
	ptr := wasm2go.WasmAlloc(m.g, wptr(len(resp)))
	copy(wasm2go.Memory(m.g)[wptrOff(ptr):], resp)
	if m.cbDesc == 0 {
		m.cbDesc = wasm2go.WasmAlloc(m.g, 16)
	}
	mem := wasm2go.Memory(m.g)
	binary.LittleEndian.PutUint64(mem[wptrOff(m.cbDesc):], uint64(ptr))
	binary.LittleEndian.PutUint64(mem[wptrOff(m.cbDesc)+8:], uint64(len(resp)))
	return int64(m.cbDesc)
}

// envStubs implements wasm2go/base.EnvImports — the host side of the
// wasm "env" imports. The per-method definitions are emitted by the
// generator (generateEnvStubs) since the import set is module-specific.
type envStubs struct{ m *Module }

// RegisterCallback registers a Go callback handler and returns its ID.
// Safe to call concurrently with other Register/Unregister/callback
// dispatch calls.
func RegisterCallback(handler CallbackHandler) int32 {
	m := module()
	m.cbMu.Lock()
	defer m.cbMu.Unlock()
	if m.callbacks == nil {
		m.callbacks = make(map[int32]CallbackHandler)
	}
	m.nextCBID++
	id := m.nextCBID
	m.callbacks[id] = handler
	return id
}

// UnregisterCallback removes a previously registered callback handler.
// Safe to call concurrently with other Register/Unregister/callback
// dispatch calls.
func UnregisterCallback(id int32) {
	m := module()
	m.cbMu.Lock()
	delete(m.callbacks, id)
	m.cbMu.Unlock()
}

func (m *Module) handleCallback(callbackID, methodID int32, reqPtr, reqLen wptr) int64 {
	m.cbMu.RLock()
	handler, ok := m.callbacks[callbackID]
	m.cbMu.RUnlock()
	if !ok {
		return 0
	}
	mem := wasm2go.Memory(m.g)
	var req []byte
	if reqLen > 0 {
		buf := make([]byte, reqLen)
		copy(buf, mem[wptrOff(reqPtr):wptrOff(reqPtr)+uint64(reqLen)])
		req = buf
	}
	// Release m.mu around the user handler so that nested calls
	// back into the transpiled module can re-acquire it without
	// deadlocking. The IIFE + defer guarantees Lock is retaken even
	// if the handler panics, so the outer invoke's defer
	// m.mu.Unlock() always sees a held mutex.
	var resp []byte
	var err error
	func() {
		m.mu.Unlock()
		defer m.mu.Lock()
		resp, err = handler.HandleCallback(methodID, req)
	}()
	if err != nil {
		resp = pbAppendString(nil, 15, err.Error())
	}
	if len(resp) == 0 {
		return 0
	}
	return encodeCallbackResult(m, resp)
}

// wasmifyStubs implements wasm2go/base.WasmifyImports: the single
// callback_invoke entry point that the C++ bridge calls back into.
type wasmifyStubs struct{ m *Module }

func (h wasmifyStubs) Callback_invoke(_ *base.Module, callbackID, methodID int32, reqPtr, reqLen wptr) int64 {
	return h.m.handleCallback(callbackID, methodID, reqPtr, reqLen)
}

var _ = fmt.Errorf
var _ = sort.Search

type Token_SinkNode interface {
	rawPtr() uint64
	isToken_Sink()
	OnPiece(piece string) error
}

// cppTypeNames / cppTypeFactories: parallel sorted slices replacing
// the old cppTypeToGoType map literal. Looked up via sort.Search.
var cppTypeNames = []string{}

var cppTypeFactories = []func(uint64) any{}

// resolveAbstractHandle queries the C++ runtime for the actual type of the
// object at ptr and returns the appropriate concrete Go handle type.
func resolveAbstractHandle(ptr uint64) (any, error) {
	typeName, err := module().resolveTypeName(ptr)
	if err != nil {
		return nil, fmt.Errorf("resolveTypeName: %w", err)
	}
	i := sort.SearchStrings(cppTypeNames, typeName)
	if i < len(cppTypeNames) && cppTypeNames[i] == typeName {
		return cppTypeFactories[i](ptr), nil
	}
	return nil, fmt.Errorf("unknown C++ type %q for ptr 0x%x", typeName, ptr)
}

var _ = fmt.Errorf
var _ = runtime.SetFinalizer

type Token_SinkCallback interface {
	OnPiece(piece string) error
}

type Token_SinkCallbackDefaults struct{}

func (Token_SinkCallbackDefaults) OnPiece(piece string) error { return nil }

type token_SinkCallbackAdapter struct {
	impl Token_SinkCallback
}

func (a *token_SinkCallbackAdapter) HandleCallback(methodID int32, req []byte) ([]byte, error) {
	switch methodID {
	case 0: // OnPiece
		var piece string
		_r := &pbReader{data: req}
		for _f, _w, _ok := _r.next(); _ok; _f, _w, _ok = _r.next() {
			switch _f {
			case 1:
				piece = _r.readString()
			default:
				_r.skip(_w)
			}
		}
		err := a.impl.OnPiece(piece)
		if err != nil {
			return nil, err
		}
		return nil, nil
	}
	return nil, fmt.Errorf("unknown callback method %d", methodID)
}

var _ = errors.New
var _ = fmt.Errorf
var _ = runtime.SetFinalizer

type Token_Sink struct {
	ptr       uint64
	keepAlive []any
}

func (h *Token_Sink) rawPtr() uint64 { return h.ptr }

func (h *Token_Sink) setKeepAlive(v any) {
	if h != nil && v != nil {
		h.keepAlive = append(h.keepAlive, v)
	}
}

func (h *Token_Sink) clearPtr() {
	if h != nil {
		h.ptr = 0
	}
}

func (*Token_Sink) isToken_Sink() {}

func newToken_Sink(ptr uint64) *Token_Sink {
	h := &Token_Sink{ptr: ptr}
	runtime.SetFinalizer(h, (*Token_Sink).free)
	return h
}

func newToken_SinkNoFinalizer(ptr uint64) *Token_Sink {
	h := &Token_Sink{ptr: ptr}
	return h
}

func (h *Token_Sink) OnPiece(piece string) error {
	buf := pbAppendHandle(pbNewBuf(), 1, h.ptr)
	buf = pbAppendString(buf, 2, piece)
	_, err := invokeMethod(1, 0, buf, wasm2go.Inv_1_0)
	return err
}

func NewToken_SinkFromImpl(impl Token_SinkCallback) (*Token_Sink, error) {
	adapter := &token_SinkCallbackAdapter{impl: impl}
	id := RegisterCallback(adapter)
	buf := pbNewBuf()
	buf = pbAppendInt32(buf, 1, id)
	resp, err := invokeMethod(1, 1, buf, wasm2go.Inv_1_1)
	if err != nil {
		UnregisterCallback(id)
		return nil, err
	}
	h := newToken_Sink(readScalarAtField(resp, 1, (*pbReader).readUint64))
	runtime.SetFinalizer(h, nil)
	runtime.SetFinalizer(h, func(h *Token_Sink) { h.free(); UnregisterCallback(id) })
	return h, nil
}

func (h *Token_Sink) free() {
	if h.ptr != 0 {
		buf := pbAppendHandle(pbNewBuf(), 1, h.ptr)
		module().invoke(1, 2, buf, wasm2go.Inv_1_2)
		h.ptr = 0
	}
}

var _ = errors.New
var _ = fmt.Errorf
var _ = runtime.SetFinalizer

// Apply the model's chat template to `messages_json`
// (`[{"role":"user","content":"hi"}, ...]`) and return the prompt string:
// `{"ok":true,"prompt":"..."}`. `add_assistant` appends the generation
// prefix. When the GGUF carries no template, `template_override` is used;
// when both are absent the call fails.
func LlamaChatApplyTemplate(model uint64, messagesJson string, messagesJsonLen uint32, templateOverride string, templateOverrideLen uint32, addAssistant int32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	buf = pbAppendString(buf, 2, messagesJson)
	buf = pbAppendUint64(buf, 3, uint64(messagesJsonLen))
	buf = pbAppendString(buf, 4, templateOverride)
	buf = pbAppendUint64(buf, 5, uint64(templateOverrideLen))
	buf = pbAppendInt32(buf, 6, addAssistant)
	resp, err := invokeMethod(0, 0, buf, wasm2go.Inv_0_0)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Rebuild and attach the context's ggml threadpool. An instance forked
//
//	from a snapshot inherits the memory image of a context whose pool
//	references worker threads of the snapshot builder; those threads do not
//	exist in this process, so the next decode (or the join inside
//	llama_ctx_free) would wait forever. Call this right after forking: it
//	creates a fresh pool with n_threads workers (poll=0, as llama_ctx_new)
//	and attaches it, ABANDONING the inherited pool struct -- its memory is
//	shared snapshot pages and its dead threads cannot be joined. n_threads
//
// <
// = 1 detaches instead, and the context's n_threads / n_threads_batch
//
//	are set to the pool size (1 when detached) so graphs actually use the
//	workers. Returns {"ok":true,"n_threads":N,"n_threads_batch":N} — the
//	counts the context now computes with — or an error object.
func LlamaCtxAttachThreadpool(ctx uint64, nThreads uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendUint64(buf, 2, uint64(nThreads))
	resp, err := invokeMethod(0, 1, buf, wasm2go.Inv_0_1)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

func LlamaCtxEmbed(ctx uint64, text string, textLen uint32, normalize int32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendString(buf, 2, text)
	buf = pbAppendUint64(buf, 3, uint64(textLen))
	buf = pbAppendInt32(buf, 4, normalize)
	resp, err := invokeMethod(0, 2, buf, wasm2go.Inv_0_2)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Embed from token ids (a JSON array of ints) instead of text — the
// token-level twin of llama_ctx_embed, same response shape.
func LlamaCtxEmbedTokens(ctx uint64, tokensJson string, tokensJsonLen uint32, normalize int32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendString(buf, 2, tokensJson)
	buf = pbAppendUint64(buf, 3, uint64(tokensJsonLen))
	buf = pbAppendInt32(buf, 4, normalize)
	resp, err := invokeMethod(0, 3, buf, wasm2go.Inv_0_3)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Decode `text` into the context's KV cache without sampling anything —
// prompt prefill for a later llama_ctx_generate, or plain evaluation.
// Positions continue from the cache's current end; llama_ctx_reset
// starts over. Returns `{"ok":true,"n_tokens":N,"n_past":N}` where
// n_past is the total sequence length now cached.
func LlamaCtxEval(ctx uint64, text string, textLen uint32, addSpecial int32, parseSpecial int32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendString(buf, 2, text)
	buf = pbAppendUint64(buf, 3, uint64(textLen))
	buf = pbAppendInt32(buf, 4, addSpecial)
	buf = pbAppendInt32(buf, 5, parseSpecial)
	resp, err := invokeMethod(0, 4, buf, wasm2go.Inv_0_4)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Free a context.
func LlamaCtxFree(ctx uint64) error {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	_, err := invokeMethod(0, 5, buf, wasm2go.Inv_0_5)
	return err
}

// Run generation and return JSON:
//
//	{"ok":true,"text":"...","tokens":[..],"n_prompt":N,"n_cached":N,
//	 "n_decoded":N,
//	 "stop_reason":"eos"|"length"|"stop"|"interrupted","interrupted":bool,
//	 "timings":{"prompt_ms":f,"decode_ms":f}}
//
// `prompt` is tokenized with add_special=true. `params_json` carries the
// sampling configuration; every field is optional:
//
//	{"n_predict":int,          // -1 = until EOS or context end
//	 "temperature":float, "top_k":int, "top_p":float, "min_p":float,
//	 "typical_p":float, "repeat_penalty":float, "repeat_last_n":int,
//	 "presence_penalty":float, "frequency_penalty":float,
//	 "seed":uint, "grammar":"...", "stop":["..",".."],
//	 "mirostat":int,            // 0 off, 1 v1, 2 v2; replaces the
//	 "mirostat_tau":float,      // truncation samplers when set
//	 "mirostat_eta":float,
//	 "ignore_eos":int,          // non-zero: end-of-generation tokens
//	                            // are excluded from sampling
//	 "cache_prompt":int,        // non-zero: treat the prompt as the whole
//	                            // intended context, keep the longest prefix
//	                            // already in the KV cache and decode only
//	                            // the rest (n_cached reports the reuse).
//	                            // Off, the prompt appends at the cache's
//	                            // current end (Eval-prefill continuation).
//	 "logit_bias":[[token,bias],..]} // added to those tokens' logits;
//	                            // -inf forbids a token outright
//
// `sink`, when non-null, receives each piece as it is decoded — see
// llama_wasm::token_sink. The result is the same either way.
func LlamaCtxGenerate(ctx uint64, prompt string, promptLen uint32, paramsJson string, paramsJsonLen uint32, sink Token_SinkNode) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendString(buf, 2, prompt)
	buf = pbAppendUint64(buf, 3, uint64(promptLen))
	buf = pbAppendString(buf, 4, paramsJson)
	buf = pbAppendUint64(buf, 5, uint64(paramsJsonLen))
	buf = pbAppendHandlePtr(buf, 6, sink)
	resp, err := invokeMethod(0, 6, buf, wasm2go.Inv_0_6)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// llama_ctx_generate_speculative is llama_ctx_generate accelerated by a
// draft context over a smaller model with the SAME vocabulary: the draft
// proposes up to `n_draft` greedy tokens per round (0 = a default) and the
// target verifies them in one batch, emitting only tokens its own sampler
// chain picked — the output distribution is exactly the target's, the
// draft only shifts decode work into larger batches.
//
// Self-contained: both contexts' caches restart from the prompt. The
// response is llama_ctx_generate's plus `"n_drafted"` / `"n_accepted"`,
// the speculation efficiency counters.
func LlamaCtxGenerateSpeculative(ctx uint64, draftCtx uint64, prompt string, promptLen uint32, paramsJson string, paramsJsonLen uint32, nDraft int32, sink Token_SinkNode) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendUint64(buf, 2, draftCtx)
	buf = pbAppendString(buf, 3, prompt)
	buf = pbAppendUint64(buf, 4, uint64(promptLen))
	buf = pbAppendString(buf, 5, paramsJson)
	buf = pbAppendUint64(buf, 6, uint64(paramsJsonLen))
	buf = pbAppendInt32(buf, 7, nDraft)
	buf = pbAppendHandlePtr(buf, 8, sink)
	resp, err := invokeMethod(0, 7, buf, wasm2go.Inv_0_7)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Address of this context's interrupt flag (a uint32 in linear memory).
// Writing a non-zero value from another thread makes the running
// llama_ctx_generate stop at its next token and return what it has, with
// `"interrupted":true`. The generation loop clears the flag when it starts.
func LlamaCtxInterruptAddr(ctx uint64) (uint64, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	resp, err := invokeMethod(0, 8, buf, wasm2go.Inv_0_8)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint64), nil
}

// Set the FULL adapter configuration of a context: `adapters_json` is
// `[[adapter_handle,scale],...]`; an empty array clears every adapter.
func LlamaCtxLoraSet(ctx uint64, adaptersJson string, adaptersJsonLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendString(buf, 2, adaptersJson)
	buf = pbAppendUint64(buf, 3, uint64(adaptersJsonLen))
	resp, err := invokeMethod(0, 9, buf, wasm2go.Inv_0_9)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Create a context over `model`. `params_json` carries the context
// parameters; absent fields take llama.cpp's defaults:
//
//	n_ctx           0 = the model's training context length
//	n_batch         logical batch size
//	n_ubatch        physical batch size
//	n_threads       0 = 1; a single-threaded wasm build clamps to 1
//	embeddings      non-zero puts the context in embedding mode
//	rope_freq_base  RoPE base frequency override (0 = model default)
//	rope_freq_scale RoPE frequency scaling override (0 = model default)
func LlamaCtxNew(model uint64, paramsJson string, paramsJsonLen uint32) (uint64, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	buf = pbAppendString(buf, 2, paramsJson)
	buf = pbAppendUint64(buf, 3, uint64(paramsJsonLen))
	resp, err := invokeMethod(0, 10, buf, wasm2go.Inv_0_10)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint64), nil
}

// Drop the context's KV cache so the next generation starts fresh.
func LlamaCtxReset(ctx uint64) error {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	_, err := invokeMethod(0, 11, buf, wasm2go.Inv_0_11)
	return err
}

// Embed `text` with a context created with embeddings=1 and return
// `{"ok":true,"embedding":[..],"n_embd":N}`. `normalize` applies L2
// normalisation (2 = euclidean, 0 = none), matching llama.cpp's convention.
//
// llama_ctx_score computes the teacher-forced negative log-likelihood of
// `text`: tokenize (add_special, parse_special), decode once with logits at
// every predicting position, and sum -log softmax(logits_i)[token_{i+1}].
// Returns `{"ok":true,"n_tokens":N,"n_scored":N-1,"nll":X}`. The float-
// tolerant compatibility gate compares this against native llama.cpp
// perplexity on the same text.
func LlamaCtxScore(ctx uint64, text string, textLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendString(buf, 2, text)
	buf = pbAppendUint64(buf, 3, uint64(textLen))
	resp, err := invokeMethod(0, 12, buf, wasm2go.Inv_0_12)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// llama_ctx_score_choices scores candidate continuations of the CURRENT
// cache state: `choices` is a newline-separated list of candidate texts, and
// for each one the call returns the negative log-likelihood of its tokens as
// the continuation of what the context has already decoded. Precondition:
// the caller has just decoded the shared stem (llama_ctx_eval or the prompt
// phase of generate), so the logits of the next position are live — the
// first token of every choice is scored from those shared logits, the rest
// teacher-forced. Each choice's tokens are decoded and then rolled back
// (llama_memory_seq_rm), so the cache — and prefix-history bookkeeping — end
// exactly where they started and the choices never see each other. Returns
// `{"ok":true,"scores":[{"n_tokens":K,"nll":X},...]}` in input order.
func LlamaCtxScoreChoices(ctx uint64, choices string, choicesLen uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendString(buf, 2, choices)
	buf = pbAppendUint64(buf, 3, uint64(choicesLen))
	resp, err := invokeMethod(0, 13, buf, wasm2go.Inv_0_13)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Restore a context state previously produced by llama_ctx_state_save.
// `data` carries the serialized bytes (the bridge copies them into
// linear memory; they may contain NUL bytes). A blob from this bridge also
// restores the prefix history for cache_prompt; a bare llama-state blob
// (an older bridge's) restores with the history invalid, so the next
// cache_prompt generate rebuilds from scratch.
func LlamaCtxStateLoad(ctx uint64, data string, size uint32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	buf = pbAppendString(buf, 2, data)
	buf = pbAppendUint64(buf, 3, uint64(size))
	resp, err := invokeMethod(0, 14, buf, wasm2go.Inv_0_14)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Serialize the context state (KV cache + RNG) into the context's state
// buffer and return `{"ok":true,"addr":N,"size":N}` — the caller reads that
// many bytes at that linear-memory address. The buffer stays valid until the
// next state call on this context. The blob also carries the prefix-history
// tokens in a bridge envelope, so a restored context composes with the
// generate params' cache_prompt without a rebuild.
func LlamaCtxStateSave(ctx uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, ctx)
	resp, err := invokeMethod(0, 15, buf, wasm2go.Inv_0_15)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Render tokens (a JSON array of ints) back to text:
// `{"ok":true,"text":"..."}`.
func LlamaDetokenize(model uint64, tokensJson string, tokensJsonLen uint32, renderSpecial int32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	buf = pbAppendString(buf, 2, tokensJson)
	buf = pbAppendUint64(buf, 3, uint64(tokensJsonLen))
	buf = pbAppendInt32(buf, 4, renderSpecial)
	resp, err := invokeMethod(0, 16, buf, wasm2go.Inv_0_16)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Free a loaded adapter. Adapters still set on a context must be cleared
// (llama_ctx_lora_set with an empty array) first.
func LlamaLoraFree(adapter uint64) error {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, adapter)
	_, err := invokeMethod(0, 17, buf, wasm2go.Inv_0_17)
	return err
}

// Load a LoRA adapter GGUF for `model`. Returns an adapter handle, or 0
// (see llama_wasm_last_error). The adapter must not outlive its model.
func LlamaLoraLoad(model uint64, path string, pathLen uint32) (uint64, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	buf = pbAppendString(buf, 2, path)
	buf = pbAppendUint64(buf, 3, uint64(pathLen))
	resp, err := invokeMethod(0, 18, buf, wasm2go.Inv_0_18)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint64), nil
}

// Free a model. Contexts created from it must be freed first.
func LlamaModelFree(model uint64) error {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	_, err := invokeMethod(0, 19, buf, wasm2go.Inv_0_19)
	return err
}

// JSON metadata for a loaded model: architecture, parameter count, context
// length, embedding dimension, layer/head counts, rope type, vocabulary size,
// and the chat template when the GGUF carries one.
func LlamaModelInfo(model uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	resp, err := invokeMethod(0, 20, buf, wasm2go.Inv_0_20)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Load a GGUF model from `path` and return an opaque handle (0 on failure;
// call llama_wasm_last_error for the reason).
//
// `n_gpu_layers` is accepted and ignored — a wasm build has no GPU backend —
// so callers can pass a config through unchanged.
//
// `use_mmap` is likewise accepted for API symmetry: WASI has no usable mmap,
// so the loader always reads the file. Progress is reported through the
// progress flag described at llama_model_load_progress_addr.
func LlamaModelLoad(path string, pathLen uint32, nGpuLayers int32, useMmap int32) (uint64, error) {
	buf := pbNewBuf()
	buf = pbAppendString(buf, 1, path)
	buf = pbAppendUint64(buf, 2, uint64(pathLen))
	buf = pbAppendInt32(buf, 3, nGpuLayers)
	buf = pbAppendInt32(buf, 4, useMmap)
	resp, err := invokeMethod(0, 21, buf, wasm2go.Inv_0_21)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint64), nil
}

// Address, in linear memory, of a float the loader updates with its progress
// (0.0 .. 1.0) while llama_model_load runs. A host thread can poll it to drive
// a progress bar. Valid for the lifetime of the wasm instance.
func LlamaModelLoadProgressAddr() (uint64, error) {
	buf := pbNewBuf()
	resp, err := invokeMethod(0, 22, buf, wasm2go.Inv_0_22)
	if err != nil {
		return 0, err
	}
	return readScalarAtField(resp, 1, (*pbReader).readUint64), nil
}

// JSON list of the model's weight tensors:
//
//	{"ok":true,"tensors":[{"name":"blk.0.attn_q.weight","type":"q4_K",
//	"ne":[1536,1536],"buffer":"CPU_REPACK","vec_dot_type":"q8_K"},...]}
//	buffer is the ggml backend buffer holding the tensor ("CPU_REPACK" when
//	the CPU backend repacked it for its GEMV/GEMM kernels, "CPU" otherwise),
//	vec_dot_type the activation type its dot product quantizes to.
func LlamaModelTensors(model uint64) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	resp, err := invokeMethod(0, 23, buf, wasm2go.Inv_0_23)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// The text piece a single token renders to, as JSON `{"ok":true,"text":".."}`.
// Byte-level tokens can render to invalid UTF-8 on their own; the caller is
// expected to accumulate pieces.
func LlamaTokenToPiece(model uint64, token int32, renderSpecial int32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	buf = pbAppendInt32(buf, 2, token)
	buf = pbAppendInt32(buf, 3, renderSpecial)
	resp, err := invokeMethod(0, 24, buf, wasm2go.Inv_0_24)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Tokenize `text` and return JSON `{"ok":true,"tokens":[..]}`.
// `add_special` adds BOS/EOS per the model's convention; `parse_special`
// lets special-token text (e.g. "<|im_start|>") tokenize as that token.
func LlamaTokenize(model uint64, text string, textLen uint32, addSpecial int32, parseSpecial int32) (string, error) {
	buf := pbNewBuf()
	buf = pbAppendUint64(buf, 1, model)
	buf = pbAppendString(buf, 2, text)
	buf = pbAppendUint64(buf, 3, uint64(textLen))
	buf = pbAppendInt32(buf, 4, addSpecial)
	buf = pbAppendInt32(buf, 5, parseSpecial)
	resp, err := invokeMethod(0, 25, buf, wasm2go.Inv_0_25)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// JSON describing the build: llama.cpp version, the ggml backends compiled in,
// and whether this wasm was built with SIMD / threads. Diagnostics only.
func LlamaWasmBuildInfo() (string, error) {
	buf := pbNewBuf()
	resp, err := invokeMethod(0, 26, buf, wasm2go.Inv_0_26)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}

// Free process-wide backend state. After this every handle is invalid.
func LlamaWasmFree() error {
	buf := pbNewBuf()
	_, err := invokeMethod(0, 27, buf, wasm2go.Inv_0_27)
	return err
}

// Initialize the ggml backend registry. Idempotent; called automatically by
// llama_model_load, so an embedder normally never calls it.
func LlamaWasmInit() error {
	buf := pbNewBuf()
	_, err := invokeMethod(0, 28, buf, wasm2go.Inv_0_28)
	return err
}

// The message for the most recent failed call on this thread, or "" when the
// last call succeeded. Calls that return JSON carry their own "error" field;
// this exists for the handle-returning calls, which can only signal 0.
func LlamaWasmLastError() (string, error) {
	buf := pbNewBuf()
	resp, err := invokeMethod(0, 29, buf, wasm2go.Inv_0_29)
	if err != nil {
		return "", err
	}
	return readScalarAtField(resp, 1, (*pbReader).readString), nil
}
